- name: test playbook
  hosts: all
  connection: local
  gather_facts: true
  tasks:
    - name: set_fact
      set_fact:
        ssh1: "{{ ansible_os_name }}"
    - debug: var=ssh1
    - name: debug
      debug:
        msg: "{{ lookup('env',ansible_os_name) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh2) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh3) }}"
    - name: debug
      debug:
        msg: "{{ lookup('file', ssh4) }}"
