- name: test playbook
  hosts: all
  connection: local
  gather_facts: true
  tasks:
 - name: gather OS version
  set_facts:
     os_ver: "{{lookup('env','ansible_os_version')|default('ALL',True)| regex_replace ('[^\\d]','')}}"
- name: copy cve files
  win_copy:
    src: files/Windows_server_{{os_ver}}
    dest: C:\windows\temp\Windows_server_{{os_ver}}
