- name: test playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: gather OS version
      set_fact:
        os_ver: "{{lookup(env,'ansible_os_name')|default('ALL',True)}}"
    - name: copy cve files
      win_copy:
        src: files/Windows_server_{{os_ver}}
        dest: C:\windows\temp\Windows_server_{{os_ver}}
