---
- name: Socks connection
  hosts: localhost
  connection: local
  any_errors_fatal: true
  vars:
    acc_id: "{{ blueid_shortcode }}"
    transaction_id: "{{ tower_job_id }}"
  roles:
    - role: ansible-role-event-socks-tunnel
  tags:
    - socks

- name: Create AD windows non admin account
  hosts: all
  #vars:
   #   machine_user: "{{ ansible_user }}"

  roles:
    - role: create_ad_win_user_non_admin
