---
- name: Configuration of WMI
  block:
    - name: Config security for RootSDDL
      ansible.windows.win_powershell:
        script: "{{ lookup('file', 'Set-WmiNamespaceSecurity.ps1') }}"
        parameters:
          user: "{{ sl1_account_name }}"
          log_filepath: 'C:\\schneider\\scriptingpath\\'
          debug_all: true
      notify:
        - Restart wmi

    - name: Allow user to check services
      ansible.windows.win_powershell:
        script: "{{ lookup('file', 'Set-ServicePermissions.ps1') }}"
        parameters:
          user: "{{ sl1_account_name }}"
          log_filepath: 'C:\\schneider\\scriptingpath\\'
          debug_all: true

  rescue:
    - name: Could not create user. Generate error.
      debug:
        msg: "error"
